name: Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # every UTC midnight

env:
  DENO_VERSION: 1.45

jobs:
  spec:
    name: Hrana Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Download
        run: deno task spec

      - name: Different
        env:
          FILE: hrana-v3.md
        run: |
          deno fmt $FILE
          if git diff --name-only --exit-code $FILE; then
            echo "-> spec is up to date!"
          else
            echo "::error::Hrana spec is outdated!"
            exit 1
          fi
